spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/olb-notification-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Kafka configuration
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 9095

# rabbitMQ configuration
newBookAdded:
  exchange: new_book_added_exchange
  queue: new_book_added_queue
  anything:
    routing-key: new_book.*

newBook:
  added:
    key: new_book.added

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

aws:
  lambda:
    function-url: ${AWS_LAMBDA_FUNCTION_URL}
