spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Kafka configuration
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
server:
  port: ${SERVER_PORT}

# rabbitMQ configuration
newBookAdded:
  exchange: new_book_added_exchange
  queue: new_book_added_queue
  anything:
    routing-key: new_book.*

newBook:
  added:
    key: new_book.added

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}

aws:
  lambda:
    function-url: ${AWS_LAMBDA_FUNCTION_URL}
