spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/account/**
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/books/**
          filters:
            - BookServiceSecurityFilter

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}