spring:
  application:
    name: book-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  content:
    fs:
      filesystem-root: ${CONTENT_PATH}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  #Kafka configuration
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}

server:
  port: ${SERVER_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}

# rabbitMQ configuration
newBookAdded:
  exchange: new_book_added_exchange
newBook:
  added:
    key: new_book.added
