spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/olb-book-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  content:
    fs:
      filesystem-root: /Users/daria/Facultate/Master/An2/Sem1/service-oriented-architectures/olb-data/files

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

# rabbitMQ configuration
newBookAdded:
  exchange: new_book_added_exchange
newBook:
  added:
    key: new_book.added
